---
- name: Create compose file
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ auto_sticker_pinner_compose_path }}'
    owner: 'dockremap'
    group: 'docker'
    mode: 0640

# Take into account additional docker-compose.yml files.
- name: Find all Docker Compose files
  find:
    paths: '{{ auto_sticker_pinner_service_path }}'
    patterns: 'docker-compose*.yml'
    recurse: false
  register: found_compose

- name: Create containers
  docker_compose:
    project_src: '{{ auto_sticker_pinner_service_path }}'
    files: '{{ found_compose.files | map(attribute="path") | list }}'
    state: '{{ compose_state }}'
    restarted: '{{ compose_restart }}'
    recreate: '{{ compose_recreate | default("smart") }}'
