---
- name: Wait for Admin port to be available
  wait_for:
    port: '{{ ipfs_admin_port }}'
    delay: 5
  when: ipfs_container.changed

- name: Configure IPFS MaxStorage
  command: |
    docker exec {{ ipfs_cont_name }}
      ipfs config --json
      'Datastore.StorageMax'
      '"{{ ipfs_max_storage }}"'

- name: Configure IPFS settings
  command: |
    docker exec {{ ipfs_cont_name }}
      ipfs config --json
      '{{ item.key }}'
      '{{ item.value | to_json }}'
  with_dict: '{{ ipfs_config }}'
