---
- name: 'Start container: {{ ipfs_cont_name }}'
  docker_container:
    name: '{{ ipfs_cont_name }}'
    image: '{{ ipfs_cont_image }}'
    pull: true
    restart_policy: always
    state: '{{ cont_state }}'
    recreate: '{{ cont_recreate }}'
    restart: '{{ cont_restart }}'
    env:
      # https://github.com/ipfs/go-ipfs/blob/master/docs/config.md
      IPFS_PROFILE: server
      IPFS_LOGGING_FMT: 'nocolor'
    command: |
      daemon
      {% if ipfs_debug_enabled %}
      --debug
      {% endif %}
    ports:
      - '127.0.0.1:{{ ipfs_admin_port }}:{{ ipfs_admin_port }}/tcp'
      - '{{ ipfs_swarm_port }}:{{ ipfs_swarm_port }}/tcp'
      - '{{ ipfs_gateway_port }}:{{ ipfs_gateway_port }}/tcp'
    volumes:
      - '{{ ipfs_cont_vol }}/data:/data/ipfs'
