---
# Fix for 'failed to sufficiently increase receive buffer size'
# https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size
- name: Increase max socket receive buffer size
  sysctl:
    name: 'net.core.rmem_max'
    value: '2500000'
    sysctl_set: true

- name: Create container directory
  file:
    path: '{{ ipfs_cont_vol }}'
    owner: '{{ ipfs_host_uid }}'
    group: 'docker'
    state: 'directory'
    mode: 0775

- name: Create compose file
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ ipfs_compose_path }}'
    owner: '{{ ipfs_host_uid }}'
    group: 'docker'
    mode: 0640

# Take into account additional docker-compose.yml files.
- name: Find all Docker Compose files
  find:
    paths: '{{ ipfs_service_path }}'
    patterns: 'docker-compose*.yml'
    recurse: false
  register: ipfs_all_compose

- name: Create containers
  docker_compose:
    project_src: '{{ ipfs_service_path }}'
    files: '{{ ipfs_all_compose.files | map(attribute="path") | list }}'
    state: '{{ compose_state }}'
    restarted: '{{ compose_restart }}'
    recreate: '{{ compose_recreate | default("smart") }}'
    pull: true
    build: false
  register: ipfs_container
