---
- name: Enable Swarm, HTTP & HTTPS ports
  iptables:
    action: insert
    chain: DOCKER-USER
    jump: ACCEPT
    source: '0.0.0.0/0'
    protocol: 'tcp'
    comment: '{{ item.cmnt }}'
    destination_port: '{{ item.port }}'
  with_items:
    - { cmnt: 'IPFS HTTP',  port: 80 }
    - { cmnt: 'IPFS SSL',   port: 443 }
    - { cmnt: 'IPFS Swarm', port: '{{ ipfs_swarm_port }}' }
  notify:
    - Save iptables rules
