---
ipfs_cluster_domain: '{{ stage }}-{{ env }}.status.im'
ipfs_cluster_secret:  '{{lookup("passwordstore", "service/ipfs-cluster/secret")}}'
ipfs_cluster_service_cont: '{{ ipfs_cont_name }}'
ipfs_cluster_service_port: '{{ ipfs_admin_port }}'

# expose more api paths to allow adding and pinning
ipfs_api_exposed: true
ipfs_api_exposed_paths:
  - /api/v0/add
  - /api/v0/pin/add
  - /api/v0/pin/rm
  - /api/v0/object/get
