---
# CloudFlare Origin certificates
origin_certs:
  - domain: 'status.im'
    crt: '{{lookup("passwordstore", "cloud/Cloudflare/status.im/origin.crt returnall=true")}}'
    key: '{{lookup("passwordstore", "cloud/Cloudflare/status.im/origin.key returnall=true")}}'
    default: true

ipfs_cluster_secret:  '{{lookup("passwordstore", "services/ipfs-cluster/secret")}}'
ipfs_cluster_service_cont: '{{ ipfs_cont_name }}'
ipfs_cluster_service_port: '{{ ipfs_admin_port }}'

# Proxy
ipfs_proxy_domain: '{{ env }}.status.im'
ipfs_proxy_gateway_port: '{{ ipfs_gateway_port }}'
# previously this used 'ipfs_admin_port' directly
ipfs_proxy_admin_port: '{{ ipfs_cluster_proxy_port }}'
# expose more api paths to allow adding and pinning
ipfs_proxy_api_exposed: true
# BE VERY CAREFUL WHAT YOU PUT HERE
ipfs_proxy_api_exposed_paths:
  - /api/v0/id
  - /api/v0/add
  - /api/v0/get
  - /api/v0/pin/add
  - /api/v0/pin/rm
  - /api/v0/pin/ls
  - /api/v0/object/get

# lower verbosity of logs
ipfs_log_level: warn

# allow all domains for CORS
ipfs_config:
  'API.HTTPHeaders.Access-Control-Allow-Origin': ["*"]
  'API.HTTPHeaders.Access-Control-Allow-Methods': ["PUT", "GET", "POST"]
  'Addresses.Announce': ["/ip4/127.0.0.1", "/ip4/{{ ansible_host }}", "/dnsaddr/{{ dns_entry }}"]

# we default to 70% of available storage
ipfs_storage_ratio: 0.7
ipfs_storage_mount: '/'
ipfs_storage_data: |
  {{ ansible_mounts
  | selectattr('mount','equalto', ipfs_storage_mount)
  | list | first }}
ipfs_max_storage: |-
  {{ ((ipfs_storage_data["size_total"] / (10|pow(9))) * ipfs_storage_ratio)
  | round(0, "floor") | int }}GB

# Syncing with TheGraph IPFS cluster, only on the first host
ipfs_sync_timer_enabled: '{{ (hostname.split(".")|first) == "node-01" }}'
ipfs_sync_src_url: 'http://localhost:{{ ipfs_cluster_proxy_port }}/'
ipfs_sync_dest_url: 'https://api.thegraph.com/ipfs/'

# Open Nginx Ports
open_ports_default_comment: 'HTTP & HTTPS'
open_ports_list: [ {port: 80}, {port: 443} ]
