---
ipfs_cluster_domain: '{{ stage }}-{{ env }}.status.im'
ipfs_cluster_secret:  '{{lookup("passwordstore", "service/ipfs-cluster/secret")}}'
ipfs_cluster_service_cont: '{{ ipfs_cont_name }}'
ipfs_cluster_service_port: '{{ ipfs_admin_port }}'

# expose more api paths to allow adding and pinning
ipfs_api_exposed: true
ipfs_api_exposed_paths:
  - /api/v0/id
  - /api/v0/add
  - /api/v0/get
  - /api/v0/pin/add
  - /api/v0/pin/rm
  - /api/v0/pin/ls
  - /api/v0/object/get

# lower verbosity of logs
ipfs_log_level: warning

# allow all domains for CORS
ipfs_config:
  'API.HTTPHeaders.Access-Control-Allow-Origin': ["*"]
  'API.HTTPHeaders.Access-Control-Allow-Methods': ["PUT", "GET", "POST"]
  'Addresses.Announce': ["/ip4/127.0.0.1", "/ip4/{{ ansible_host }}", "/dnsaddr/{{ dns_entry }}"]

# we default to 70% of available storage
ipfs_storage_ratio: 0.7
ipfs_storage_mount: '/'
ipfs_storage_data: |
  {{ ansible_mounts
  | selectattr('mount','equalto', ipfs_storage_mount)
  | list | first }}
ipfs_max_storage: |-
  {{ ((ipfs_storage_data["size_total"] / (10|pow(9))) * ipfs_storage_ratio)
  | round(0, "floor") | int }}GB
