---
# will be used for configuring the nginx proxy
ipfs_cluster_domain: ~
# needs to be the same for all cluster members
ipfs_cluster_secret: ~

# ipfs specific settings
ipfs_cont_tag: 'v0.4.20'
ipfs_cont_image: 'ipfs/go-ipfs:{{ ipfs_cont_tag }}'
ipfs_cont_name: 'ipfs-service'
ipfs_cont_vol: '/docker/{{ ipfs_cont_name }}'
ipfs_api_port: 5001
# WARNING: this port should never be public
ipfs_swarm_port: 4001
ipfs_gateway_port: 8080

# cluster specific settings
ipfs_cluster_cont_tag: 'v0.10.1'
ipfs_cluster_cont_image: 'ipfs/ipfs-cluster:{{ ipfs_cluster_cont_tag }}'
ipfs_cluster_cont_name: 'ipfs-cluster'
ipfs_cluster_cont_vol: '/docker/{{ ipfs_cluster_cont_name }}'
ipfs_cluster_cont_uid: 1000
ipfs_cluster_host_uid: '{{ 100000 + ipfs_cluster_cont_uid - 1 | int }}'

# api settings
ipfs_cluster_rest_addr: '0.0.0.0'
ipfs_cluster_api_port: 9094
ipfs_cluster_rpc_port: 9096
ipfs_cluster_node_port: 5001
# WARNING: this port should never be public
ipfs_cluster_proxy_port: 9095

# levels: critical, error, warning, info, debug
ipfs_cluster_log_level: info

# generic container settings
cont_state: started
cont_recreate: false
cont_restart: false

# Consul query variables
consul_catalog_url: 'http://localhost:8500/v1/catalog'
consul_service_name: '{{ ipfs_cluster_cont_name }}'
