---
# needs to be the same for all cluster members
ipfs_cluster_secret: ~
# name of container to connect to
ipfs_cluster_service_cont: ~
ipfs_cluster_service_port: 5001

# address used to link ipfs-cluster with ipfs service
ipfs_cluster_service_addr: '/dns4/{{ ipfs_cluster_service_cont | mandatory }}/tcp/{{ ipfs_cluster_service_port }}'

# cluster specific settings
ipfs_cluster_cont_tag: 'v0.10.1'
ipfs_cluster_cont_image: 'ipfs/ipfs-cluster:{{ ipfs_cluster_cont_tag }}'
ipfs_cluster_cont_name: 'ipfs-cluster'
ipfs_cluster_cont_vol: '/docker/{{ ipfs_cluster_cont_name }}'
ipfs_cluster_cont_uid: 1000
ipfs_cluster_host_uid: '{{ 100000 + ipfs_cluster_cont_uid - 1 | int }}'

# Cluster Admin API
ipfs_cluster_admin_port: 5001
# Cluster REST API
ipfs_cluster_rest_addr: '0.0.0.0'
ipfs_cluster_rest_port: 9094
# port for cluster peer election viar raft
ipfs_cluster_raft_port: 9096
# WARNING: this port should never be public
ipfs_cluster_proxy_port: 9095

# levels: critical, error, warning, info, debug
ipfs_cluster_log_level: 'warning'

# generic container settings
cont_state: started
cont_recreate: false
cont_restart: false

# Consul query variables
consul_catalog_url: 'http://localhost:8500/v1/catalog'
consul_service_name: '{{ ipfs_cluster_cont_name }}'
