---
- name: Configure IPFS cluster
  hosts: ipfs
  roles:
    - { role: nodejs,        tags: nodejs }
    - { role: origin-certs,  tags: origin-certs }
    - { role: ipfs-service,  tags: ipfs-service }
    - { role: ipfs-cluster,  tags: ipfs-cluster }
    - { role: ipfs-proxy,    tags: ipfs-proxy }
    - { role: ipfs-pinner,   tags: ipfs-pinner }
    - { role: ipfs-sync,     tags: ipfs-sync }
    - { role: nginx-metrics, tags: nginx-metrics }

- name: Configure Packer Sync node
  hosts: sync
  roles:
    - { role: infra-role-geth,          tags: infra-role-geth }
    - { role: infra-role-geth-exporter, tags: infra-role-geth-exporter }
    #- { role: sticker-pinner,           tags: sticker-pinner }
