---
- name: Configure IPFS cluster
  hosts: ipfs
  roles:
    - { role: origin-cert,  tags: origin-cert }
    - { role: ipfs-service, tags: ipfs-service }
    - { role: ipfs-cluster, tags: ipfs-cluster }
