---
- name: 'Start container: {{ ipfs_cluster_cont_name }}'
  docker_container:
    name: '{{ ipfs_cluster_cont_name }}'
    image: '{{ ipfs_cluster_cont_image }}'
    pull: true
    restart_policy: always
    state: '{{ cont_state }}'
    recreate: '{{ cont_recreate }}'
    restart: '{{ ipfs_peerstore.changed | default(cont_restart) }}'
    links:
      '{{ ipfs_cluster_service_cont }}:{{ ipfs_cluster_service_cont }}'
    env:
      IPFS_LOGGING_FMT: nocolor
    command: daemon --upgrade
    ports:
      - '127.0.0.1:5002:{{ ipfs_cluster_admin_port }}/tcp'
      - '{{ ipfs_cluster_rest_port }}:{{ ipfs_cluster_rest_port }}/tcp'
      - '{{ ipfs_cluster_raft_port }}:{{ ipfs_cluster_raft_port }}/tcp'
      - '{{ ipfs_cluster_proxy_port }}:{{ ipfs_cluster_proxy_port }}/tcp'
    volumes:
      - '{{ ipfs_cluster_cont_vol }}/data:/data/ipfs-cluster'
