---
- name: Create container directories
  file:
    path: '{{ ipfs_cluster_cont_vol }}/data'
    owner: '{{ ipfs_cluster_host_uid }}'
    group: docker 
    recurse: true
    state: directory

- name: 'Start container: {{ ipfs_cluster_cont_name }}'
  docker_container:
    name: '{{ ipfs_cluster_cont_name }}'
    image: '{{ ipfs_cluster_cont_image }}'
    pull: true
    restart_policy: always
    state: '{{ cont_state }}'
    recreate: '{{ cont_recreate }}'
    restart: '{{ cont_restart }}'
    links:
      '{{ ipfs_cont_name }}:{{ ipfs_cont_name }}'
    env:
      IPFS_LOGGING_FMT: nocolor
    command: daemon --upgrade
    ports:
      - '{{ ipfs_cluster_api_port }}:{{ ipfs_cluster_api_port }}/tcp'
      - '{{ ipfs_cluster_rpc_port }}:{{ ipfs_cluster_rpc_port }}/tcp'
      - '{{ ipfs_cluster_proxy_port }}:{{ ipfs_cluster_proxy_port }}/tcp'
    volumes:
      - '{{ ipfs_cluster_cont_vol }}/data:/data/ipfs-cluster'
