---
- name: Create container directory
  file:
    path: '{{ ipfs_cluster_cont_vol }}'
    owner: '{{ ipfs_cluster_host_uid }}'
    group: docker 
    recurse: true
    state: directory

- name: Create compose file
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ ipfs_cluster_compose_path }}'
    owner: 'dockremap'
    group: 'docker'
    mode: 0640

# Take into account additional docker-compose.yml files.
- name: Find all Docker Compose files
  find:
    paths: '{{ ipfs_cluster_service_path }}'
    patterns: 'docker-compose*.yml'
    recurse: false
  register: ipfs_all_compose

- name: Create containers
  docker_compose:
    project_src: '{{ ipfs_cluster_service_path }}'
    files: '{{ ipfs_all_compose.files | map(attribute="path") | list }}'
    state: '{{ compose_state }}'
    restarted: '{{ compose_restart }}'
    recreate: '{{ compose_recreate | default("smart") }}'
    pull: true
    build: false
