---
- name: Enable IPFS Cluster ports
  iptables:
    action: insert
    chain: DOCKER-USER
    jump: ACCEPT
    source: '0.0.0.0/0'
    protocol: 'tcp'
    comment: '{{ item.cmnt }}'
    destination_port: '{{ item.port }}'
  with_items:
    - { cmnt: 'IPFS Cluster API',   port: '{{ ipfs_cluster_rest_port }}' }
    - { cmnt: 'IPFS Cluster Raft',  port: '{{ ipfs_cluster_raft_port }}' }
  notify:
    - Save iptables rules
