---
- name: Check if IPFS config exists
  stat:
    path: '{{ ipfs_cluster_cont_vol }}/data/service.json'
  register: ipfs_config

- name: Generate config for container
  docker_container:
    name: '{{ ipfs_cluster_cont_name }}-config-gen'
    image: '{{ ipfs_cluster_cont_image }}'
    auto_remove: true
    env:
      CLUSTER_SECRET: '{{ ipfs_cluster_secret }}'
      IPFS_API: '{{ ipfs_cluster_service_addr }}'
    command: init
    volumes:
      - '{{ ipfs_cluster_cont_vol }}/data:/data/ipfs-cluster'
  when: not ipfs_config.stat.exists
