---
- name: Create container directories
  file:
    path: '{{ ipfs_cluster_cont_vol }}/data'
    owner: '{{ ipfs_cluster_host_uid }}'
    group: docker 
    recurse: true
    state: directory

- name: Check if identity file exists
  stat:
    path: '{{ ipfs_cluster_identity_file }}'
  register: ipfs_cluster_identiy

# Creates service.json and identity.json.
# Necessary to have peer public key for Consul service metadata.
- name: Generate config for container
  docker_container:
    name: '{{ ipfs_cluster_service_name }}-config-gen'
    image: '{{ ipfs_cluster_cont_image }}'
    auto_remove: true
    env:
      CLUSTER_SECRET: '{{ ipfs_cluster_secret }}'
      CLUSTER_PEERNAME: '{{ ipfs_cluster_peer_name }}'
      IPFS_API: '{{ ipfs_cluster_service_addr }}'
    command: init --consensus=raft
    volumes:
      - '{{ ipfs_cluster_cont_vol }}/data:/data/ipfs-cluster'
  when: not ipfs_cluster_identiy.stat.exists
