---
- name: Get data centers
  uri:
    url: '{{ consul_catalog_url }}/datacenters'
    return_content: true
  register: data_centers

- name: Discover IPFS services
  uri:
    url: '{{ consul_catalog_url }}/service/{{ consul_service_name }}?dc={{ item }}'
    return_content: true
  register: ipfs_services_dcs
  with_items: '{{ data_centers.json }}'

- name: Combine data centers into one list
  set_fact:
    ipfs_services: '{{ ipfs_services_dcs.results | sum(attribute="json", start=[]) }}'

- name: Extract RCP addresses
  set_fact:
    ipfs_peers_rpc: '{{ ipfs_services | map(attribute="ServiceMeta") | map(attribute="ipfs_peer_rpc") | list }}'

- name: Create peerstore file
  copy:
    dest: '{{ ipfs_cluster_cont_vol }}/data/peerstore'
    content: "{{ ipfs_peers_rpc | join('\n') }}"
    owner: '{{ ipfs_cluster_host_uid }}'
    group: docker 

- name: 'Restart container: {{ ipfs_cluster_cont_name }}'
  docker_container:
    name: '{{ ipfs_cluster_cont_name }}'
    restart: true
