---
ipfs_service_name: 'ipfs-service'
ipfs_service_path: '/docker/{{ ipfs_service_name }}'
ipfs_compose_path: '{{ ipfs_service_path }}/docker-compose.yml'

# ipfs specific settings
ipfs_cont_tag: 'v0.8.0'
ipfs_cont_image: 'ipfs/go-ipfs:{{ ipfs_cont_tag }}'
ipfs_cont_name: '{{ ipfs_service_name }}'
ipfs_cont_vol: '/docker/{{ ipfs_cont_name }}'

# WARNING: this port should never be entirely public
ipfs_admin_port: 5001
# this port is for libp2p
ipfs_swarm_port: 4001
# this is the port that exposes IPFS resources and some R/O APi
ipfs_gateway_port: 8080

# available: debug, info, warn, error, dpanic, panic, fatal
ipfs_log_level: info

# hard storage limit
ipfs_max_storage: '10GB'

# config settings to adjust after container start
ipfs_config: {}

# general container management
compose_recreate: 'smart'
compose_state: 'present'
compose_restart: false
