---
# will be used for configuring the nginx proxy
ipfs_cluster_domain: ~

# ipfs specific settings
ipfs_cont_tag: 'v0.4.22'
ipfs_cont_image: 'ipfs/go-ipfs:{{ ipfs_cont_tag }}'
ipfs_cont_name: 'ipfs-service'
ipfs_cont_vol: '/docker/{{ ipfs_cont_name }}'

# WARNING: this port should never be public
ipfs_admin_port: 5001
# this port is for libp2p
ipfs_swarm_port: 4001
# this is the port that exposes IPFS resources and some R/O APi
ipfs_gateway_port: 8080

# for selective exposing some of the admin API
ipfs_api_exposed: false
ipfs_epi_exposed_timeout: '600s'
ipfs_api_exposed_max_body_size: '50m'
ipfs_api_exposed_port: 2053
ipfs_api_exposed_paths:
  - /api/v0/object/get

# available: critical, error, warning, info, debug
ipfs_log_level: info

# hard storage limit
ipfs_max_storage: '10GB'

# config settings to adjust after container start
ipfs_config: {}

# generic container settings
cont_state: started
cont_recreate: false
cont_restart: false
