---
# ipfs specific settings
ipfs_cont_tag: 'v0.5.1'
ipfs_cont_image: 'ipfs/go-ipfs:{{ ipfs_cont_tag }}'
ipfs_cont_name: 'ipfs-service'
ipfs_cont_vol: '/docker/{{ ipfs_cont_name }}'

# WARNING: this port should never be entirely public
ipfs_admin_port: 5001
# this port is for libp2p
ipfs_swarm_port: 4001
# this is the port that exposes IPFS resources and some R/O APi
ipfs_gateway_port: 8080

# available: debug, info, warn, error, dpanic, panic, fatal
ipfs_log_level: info

# hard storage limit
ipfs_max_storage: '10GB'

# config settings to adjust after container start
ipfs_config: {}

# generic container settings
cont_state: started
cont_recreate: false
cont_restart: false
